apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mohamedDev/argocd.git
        revision: main
        directories:
          - path: apps/*/* # => toutes les combinaisons apps/service/env
  template:
    metadata:
      name: "{{path[1]}}-{{path.basename}}" # Ex: users-service-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/mohamedDev/argocd.git
        targetRevision: main
        path: "{{path}}" # Ex: apps/users-service/dev
        kustomize:
          buildOptions: "--enable-helm" # ← Ajouter cette ligne
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}-{{path.basename}}" # Ex: users-service-dev
      syncPolicy:
        automated: # Synchronisation automatique
          prune: true # Supprime les ressources qui ne sont plus dans le repo git
          selfHeal: true # Répare les ressources qui ne sont plus synchronisées
        syncOptions:
          - CreateNamespace=true # Crée le namespace si il n'existe pas
          - ApplyOutOfSyncOnly=true # Applique uniquement les ressources qui ne sont pas synchronisées
