apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mohamedDev/argocd.git
        revision: main
        directories:
          - path: apps/*/* # => toutes les combinaisons apps/service/env
  template:
    metadata:
      name: "{{path[1]}}-{{path.basename}}" # Ex: users-service-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/mohamedDev/argocd.git
        targetRevision: main
        path: "{{path}}" # Ex: apps/users-service/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}-{{path.basename}}" # Ex: users-service-dev
      syncPolicy:
        automated: # Synchronisation automatique
          prune: true # Supprime les ressources qui ne sont plus dans le repo git
          selfHeal: true # Répare les ressources qui ne sont plus synchronisées
        syncOptions:
          - CreateNamespace=true # Crée le namespace si il n'existe pas
          - ApplyOutOfSyncOnly=true # Applique uniquement les ressources qui ne sont pas synchronisées

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.1.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: "admin"  # À remplacer par un Secret
          persistence:
            enabled: true
            storageClassName: standard
            size: 10Gi
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
            datasources:
              enabled: true
              defaultDatasourceEnabled: true
          plugins:
            - grafana-piechart-panel
            - grafana-worldmap-panel

        prometheus:
          enabled: true
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false

        alertmanager:
          enabled: true

        loki:
          enabled: true
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: standard

        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki.monitoring:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
