apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
