apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.3.1
          ports:
            - containerPort: 9092
              name: plaintext
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "false"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"  # Changed to service name
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"  # Added this
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP  # Added type explicitly
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka