apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000          # Port interne (pour les pods)
    targetPort: 9000    # Port du container
    nodePort: 30900     # Port externe (pour l'extérieur)
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 30901
  type: NodePort