apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-env
data:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
  KONG_PLUGINS: bundled,ai-proxy   # ⚠️ pas les autres sans licence !
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true
