apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong/kong-gateway:3.10
          ports:
            - containerPort: 8000 # Proxy
            - containerPort: 8001 # Admin API
          envFrom:
            - configMapRef:
                name: kong-env
          volumeMounts:
            - name: kong-config
              mountPath: /kong
      volumes: # <---- doit être au même niveau que containers:
        - name: kong-config
          configMap:
            name: kong-config
---

