---
---
# Kong Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.4
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/declarative/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_ADMIN_GUI_URL
          value: "http://localhost:8002"
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8001
          name: admin-api
        - containerPort: 8002
          name: admin
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8444
          name: admin-ssl
        volumeMounts:
        - name: kong-config
          mountPath: /kong/declarative/
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
# Kong Service
apiVersion: v1
kind: Service
metadata:
  name: kong
  
spec:
  type: NodePort
  selector:
    app: kong
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
    nodePort: 30000
  - name: admin-api
    port: 8001
    targetPort: 8001
    nodePort: 30001
  - name: admin
    port: 8002
    targetPort: 8002
    nodePort: 30002
---
# Kong Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    
    services:
    - name: example-service
      url: http://httpbin.org
      routes:
      - name: example-route
        paths:
        - /example
---
# Konga Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:latest
        env:
        - name: NODE_ENV
          value: "development"
        - name: KONGA_HOOK_TIMEOUT
          value: "60000"
        ports:
        - containerPort: 1337
          name: http
---
# Konga Service
apiVersion: v1
kind: Service
metadata:
  name: konga
  
spec:
  type: NodePort
  selector:
    app: konga
  ports:
  - name: http
    port: 1337
    targetPort: 1337
    nodePort: 30337