---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kongpass
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_DB_KONGA
              value: konga
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kong
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
# Kong Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:2.8
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: postgres
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kongpass
            - name: KONG_PG_DATABASE
              value: kong
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          ports:
            - containerPort: 8000
              name: proxy
            - containerPort: 8001
              name: admin
---
# Kong Service
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: kong
spec:
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30001
  type: NodePort
---
# Konga Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:latest
          env:
            - name: DB_ADAPTER
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: kong
            - name: DB_PASSWORD
              value: kongpass
            - name: DB_DATABASE
              value: konga
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 1337
---
# Konga Service
apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: kong
spec:
  selector:
    app: konga
  ports:
    - port: 1337
      targetPort: 1337
      nodePort: 30002
  type: NodePort
---

