apiVersion: v1
kind: Service
metadata:
  name: konga-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: konga-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga-postgres
  template:
    metadata:
      labels:
        app: konga-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: POSTGRES_USER
              value: konga
            - name: POSTGRES_PASSWORD
              value: konga
            - name: POSTGRES_DB
              value: konga
          ports:
            - containerPort: 5432
