apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:latest
          ports:
            - containerPort: 1337
          env:
            - name: NODE_ENV
              value: "production"
            - name: KONGA_SEED_USER
              value: "admin"
            - name: KONGA_SEED_PASSWORD
              value: "admin123"
---
apiVersion: v1
kind: Service
metadata:
  name: konga-svc
spec:
  type: LoadBalancer
  ports:
    - port: 1337
      targetPort: 1337
      name: http
  selector:
    app: konga
---
apiVersion: batch/v1
kind: Job
metadata:
  name: konga-prepare
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: konga-prepare
          image: pantsel/konga:latest
          command: ["node"]
          args: ["./bin/konga.js", "prepare", "--adapter", "sails-disk"]
