# ETCD - Base de données pour APISIX
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
data:
  etcd.conf.yml: |
    name: etcd
    data-dir: /etcd-data
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://0.0.0.0:2380
    initial-advertise-peer-urls: http://0.0.0.0:2380
    initial-cluster: etcd=http://0.0.0.0:2380
    initial-cluster-token: etcd-cluster
    initial-cluster-state: new

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.4
        command:
          - etcd
          - --config-file=/etc/etcd/etcd.conf.yml
        ports:
        - containerPort: 2379
        - containerPort: 2380
        volumeMounts:
        - name: etcd-config
          mountPath: /etc/etcd
        - name: etcd-data
          mountPath: /etcd-data
      volumes:
      - name: etcd-config
        configMap:
          name: etcd-config
      - name: etcd-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
spec:
  selector:
    app: etcd
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380

# APISIX Configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_ipv6: false
      enable_control: true
      control:
        ip: "0.0.0.0"
        port: 9092
    
    deployment:
      admin:
        admin_key:
          - name: "admin"
            key: edd1c9f034335f136f87ad84b625c8f1
            role: admin
        enable_admin_cors: true
        admin_listen:
          ip: 0.0.0.0
          port: 9180
    
    etcd:
      host:
        - "http://etcd-service:2379"
      prefix: "/apisix"
      timeout: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:3.6.0-debian
        ports:
        - containerPort: 9080
        - containerPort: 9180
        - containerPort: 9092
        volumeMounts:
        - name: apisix-config
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
        env:
        - name: APISIX_STAND_ALONE
          value: "false"
      volumes:
      - name: apisix-config
        configMap:
          name: apisix-config

---
apiVersion: v1
kind: Service
metadata:
  name: apisix-service
spec:
  selector:
    app: apisix
  type: NodePort
  ports:
  - name: gateway
    port: 9080
    targetPort: 9080
    nodePort: 30080
  - name: admin
    port: 9180
    targetPort: 9180
    nodePort: 30180

# APISIX Dashboard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-dashboard-config
data:
  conf.yaml: |
    conf:
      listen:
        host: 0.0.0.0
        port: 9000
      etcd:
        endpoints:
          - etcd-service:2379
        prefix: "/apisix"
        mtls:
          key_file: ""
          cert_file: ""
          ca_file: ""
      log:
        error_log:
          level: warn
          file_path: logs/error.log
        access_log:
          file_path: logs/access.log
      max_cpu: 0
      security:
        content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src *"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix-dashboard
  template:
    metadata:
      labels:
        app: apisix-dashboard
    spec:
      containers:
      - name: apisix-dashboard
        image: apache/apisix-dashboard:3.0.1-alpine
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: dashboard-config
          mountPath: /usr/local/apisix-dashboard/conf/conf.yaml
          subPath: conf.yaml
        env:
        - name: APISIX_DASHBOARD_VERSION
          value: "3.0.1"
      volumes:
      - name: dashboard-config
        configMap:
          name: apisix-dashboard-config

---
apiVersion: v1
kind: Service
metadata:
  name: apisix-dashboard-service
spec:
  selector:
    app: apisix-dashboard
  type: NodePort
  ports:
  - name: dashboard
    port: 9000
    targetPort: 9000
    nodePort: 30000

# Service de test simple (optionnel)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test-backend-service
spec:
  selector:
    app: test-backend
  ports:
  - name: http
    port: 80
    targetPort: 80