apiVersion: v1
kind: Service
metadata:
  name: apisix
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9080
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 9443
      nodePort: 30443
      name: https
  selector:
    app: apisix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
        - name: apisix
          image: apache/apisix:3.9.0-debian
          ports:
            - containerPort: 9080
            - containerPort: 9443
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
              name: apisix-config
      volumes:
        - name: apisix-config
          configMap:
            name: apisix-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
data:
  config.yaml: |
    deployment:
      role: data_plane
      role_data_plane:
        config_provider: etcd

    etcd:
      host:
        - "http://etcd:2379"
      prefix: "/apisix" 
      timeout: 30

    plugins:  # activer les plugins nécessaires
      - key-auth
      - proxy-rewrite
      - limit-count
      - prometheus

    nginx_config:
      worker_processes: "auto"
      error_log: "logs/error.log"
      http:
        access_log: "logs/access.log"
