apiVersion: v1
kind: Service
metadata:
  name: apisix-dashboard
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30900
  selector:
    app: apisix-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix-dashboard
  template:
    metadata:
      labels:
        app: apisix-dashboard
    spec:
      containers:
        - name: dashboard
          image: apache/apisix-dashboard:3.0.1
          ports:
            - containerPort: 9000
          env:
            - name: APIX_ETCD_HOST
              value: "http://etcd:2379"
