apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: | # défini un ConfigMap avec un fichier virtuel nommé elasticsearch.yml
    node.name: single-node
    network.host: 0.0.0.0
