# PV SANS storageClassName
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/c/Users/Mohamed.Bouaziz/kubernates-shared-volume/elasticsearch-data/prod
