apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton
          image: nvcr.io/nvidia/tritonserver:23.10-py3
          args: ["tritonserver", "--model-repository=/models"]
          ports:
            - containerPort: 8000 # HTTP
            - containerPort: 8001 # gRPC
            - containerPort: 8002 # Metrics
          volumeMounts:
            - name: model-volume
              mountPath: /models
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: test
