apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data

helmGlobals:
  chartHome: ../../../charts/

helmCharts:
  - name: mlflow
    releaseName: mlflow
    namespace: data
    valuesFile: values.yaml
    valuesInline:
      image:
        repository: burakince/mlflow
        pullPolicy: IfNotPresent
        tag: 3.3.2
