backendStore:
  databaseMigration: true
  databaseConnectionCheck: false
  defaultSqlitePath: ":memory:"
  postgres:
    enabled: true  # Activé pour utiliser PostgreSQL
    host: postgres-service.postgres-dev.svc.cluster.local
    port: 5432
    database: mlflow
    user: ""  # Sera ignoré car on utilise existingDatabaseSecret
    password: ""  # Sera ignoré car on utilise existingDatabaseSecret
    driver: "psycopg2"  # Driver PostgreSQL
  mysql:
    enabled: false
    host: ""
    port: 3306
    database: ""
    user: ""
    password: ""
    driver: ""
  existingDatabaseSecret:
    name: "postgres-credentials"
    usernameKey: "username"
    passwordKey: "password"

artifactRoot:
  proxiedArtifactStorage: false
  defaultArtifactRoot: "./mlruns"
  defaultArtifactsDestination: "./mlartifacts"
  gcs:
    enabled: false
    bucket: ""
    path: ""
  s3:
    enabled: true
    bucket: mlds-models-catalog-prod
    path: "models"
    # Propriétés correctes selon le schéma
    awsAccessKeyId: "minioadmin"
    awsSecretAccessKey: "minioadmin"
    existingSecret:
      name: ""
      keyOfAccessKeyId: ""
      keyOfSecretAccessKey: ""
  azureBlob:
    enabled: false
    container: ""
    storageAccount: ""
    path: ""
    connectionString: ""
    accessKey: ""

# Configuration de l'endpoint MinIO via extraEnvVars
extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.minio-dev.svc.cluster.local:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_IGNORE_TLS: true

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

serviceMonitor:
  enabled: true
  useServicePort: false
  namespace: "monitoring"
  interval: "30s"
  telemetryPath: "/metrics"
  labels:
    release: "prometheus"
  timeout: "10s"
  targetLabels: []
  metricRelabelings: []

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

service:
  enabled: true
  type: ClusterIP
  port: 5000
  containerPort: 5000
  name: http
  containerPortName: mlflow
  annotations: {}

# Ajout des propriétés requises manquantes
postgresql:
  enabled: false  # Désactivé car on utilise un PostgreSQL externe
  architecture: "standalone"
  auth:
    username: ""
    password: ""
    database: "mlflow"
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      existingClaim: ""

mysql:
  enabled: false
  architecture: "standalone"
  auth:
    username: ""
    password: ""
    database: "mlflow"
  primary:
    service:
      ports:
        mysql: 3306
    persistence:
      enabled: true
      existingClaim: ""