apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  namespace: triton
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton
          image: nvcr.io/nvidia/tritonserver:23.10-py3
          args: ["tritonserver", "--model-repository=/models"]
          ports:
            - containerPort: 8000 # HTTP
            - containerPort: 8001 # gRPC
            - containerPort: 8002 # Metrics
          volumeMounts:
            - name: model-volume
              mountPath: /models
          resources:
            limits:
              nvidia.com/gpu: 1 # Enlever si tu n'utilises pas de GPU
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: triton-models-pvc
