apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode-server
  template:
    metadata:
      labels:
        app: vscode-server
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: PASSWORD
              value: "vscode123"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
          securityContext:                # 👇 Ajout ici
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: python-vlm-dev
      securityContext:                   # 👇 fsGroup ici pour le volume
        fsGroup: 1000
