apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-runner
  template:
    metadata:
      labels:
        app: python-runner
    spec:
      containers:
        - name: python
          image: python:3.10-slim
          ports:
            - containerPort: 8001
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: shared-models
              mountPath: /workspace
      volumes:
        - name: shared-models
          persistentVolumeClaim:
            claimName: python-vlm-dev

---
apiVersion: v1
kind: Service
metadata:
  name: python-runner-service
spec:
  selector:
    app: python-runner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP  # ou NodePort ou LoadBalancer selon ton besoin


# kubectl exec -it <pod-name> -- bash
# apt update && apt install -y pip
# pip install fastapi uvicorn transformers
# pip install tritonclient[http] numpy sentencepiece sacremoses
# uvicorn server:app --host 0.0.0.0 --port 8001
