apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-runner
  template:
    metadata:
      labels:
        app: python-runner
    spec:
      containers:
        - name: python
          image: python:3.10-slim
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: shared-models
              mountPath: /workspace
      volumes:
        - name: shared-models
          persistentVolumeClaim:
            claimName: python-vlm-dev
