apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# Route utilisant la configuration réutilisable
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kafka-route
spec:
  http:
    - name: kafka-logger-route
      match:
        hosts:
          - nginx.local
        paths:
          - /*
      backends:
        - serviceName: nginx-service
          servicePort: 80
          weight: 100
      plugins:
        - name: kafka-logger
          enable: true
          config:
            brokers:
              - host: kafka-service.apisix-dev.svc.cluster.local
                port: 9092
            kafka_topic: apisix-logs
            key: request-log
        - name: prometheus
          enable: true
          config:
            prefer_name: true
