apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# Route utilisant la configuration réutilisable
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kafka-route
spec:
  http:
    - name: kafka-logger-route
      match:
        hosts:
          - nginx.local
        paths:
          - /*
      backends:
        - serviceName: nginx-service
          servicePort: 80
          weight: 100
      plugins:
        - name: kafka-logger
          enable: true
          config:
            brokers:
              - host: kafka-service.apisix-dev.svc.cluster.local
                port: 9092
            kafka_topic: apisix-logs
            key: request-log
        - name: prometheus
          enable: true
          config:
            prefer_name: true
        - name: elasticsearch-logger
          enable: true
          config:
            endpoint_addr: "http://elasticsearch.my-elasticsearch-prod.svc.cluster.local:9200"
            field:
              index: "apisix-logs"
            timeout: 10
            batch_max_size: 100
            inactive_timeout: 5
            buffer_duration: 60
            max_retry_count: 3
            retry_delay: 1
            include_req_body: false
            include_resp_body: false
