apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-stack
  podMonitorSelector:
    matchLabels:
      release: prometheus-stack
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi