apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
spec:
  dockerImage: thegrandpkizzle/spilo-15:3.0-p1.15
  teamId: "med"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users:
    mldsadmin:
      - superuser
      - createdb
  databases:
    mlflow: mldsadmin
  postgresql:
    version: "15"
    parameters:
      max_connections: "300"
      idle_in_transaction_session_timeout: "300000" # 5 minutes
      statement_timeout: "600000" # 10 minutes

  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
    pg_hba:
      # Connexions locales
      - local all all trust
      # Connexions depuis le cluster (avec et sans SSL)
      - host all all 10.0.0.0/8 md5
      - hostssl all all 10.0.0.0/8 md5
      - hostnossl all all 10.0.0.0/8 md5
      # Réplication
      - host replication +zalandos samenet trust
      - hostssl replication +zalandos samenet trust

  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
