apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    application: spilo
    cluster-name: postgres
    spilo-role: master
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
