suite: test auth postgres secret

templates:
  - auth_postgres_secret.yaml

tests:
  - it: should be empty when auth is not enabled
    set:
      auth:
        enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should be empty when postgres is not enabled
    set:
      auth:
        enabled: true
        postgres:
          enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should be empty when existingSecret.name is set
    set:
      auth:
        enabled: true
        postgres:
          enabled: true
          existingSecret:
            name: something
    asserts:
      - hasDocuments:
          count: 0

  - it: should require postgres username when postgres.user is not set
    set:
      auth:
        enabled: true
        postgres:
          enabled: true
          user: ""
          password: thisisnotasecret
    asserts:
      - failedTemplate:
          errorMessage: "auth.postgres.user must be specified"

  - it: should require postgres password when postgres.password is not set
    set:
      auth:
        enabled: true
        postgres:
          enabled: true
          user: thisisnotasecret
          password: ""
    asserts:
      - failedTemplate:
          errorMessage: "auth.postgres.password must be specified"

  - it: should set admin username and admin password when auth enabled and both are set
    set:
      auth:
        enabled: true
        postgres:
          enabled: true
          user: postgresauthuser
          password: postgresauthpass
    asserts:
      - equal:
          path: data.username
          value: postgresauthuser
          decodeBase64: true
      - equal:
          path: data.password
          value: postgresauthpass
          decodeBase64: true
    