suite: test auth admin secret

templates:
  - auth_admin_secret.yaml

tests:
  - it: should be empty when auth is not enabled
    set:
      auth:
        enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should be empty when existingAdminSecret.name is set
    set:
      auth:
        enabled: true
        existingAdminSecret:
          name: something
    asserts:
      - hasDocuments:
          count: 0

  - it: should require admin username when adminUsername is not set
    set:
      auth:
        enabled: true
        adminUsername: ""
        adminPassword: "thisisnotasecret"
    asserts:
      - failedTemplate:
          errorMessage: "auth.adminUsername must be specified"

  - it: should require admin password when adminPassword is not set
    set:
      auth:
        enabled: true
        adminUsername: "thisisnotasecret"
        adminPassword: ""
    asserts:
      - failedTemplate:
          errorMessage: "auth.adminPassword must be specified"

  - it: should set admin username and admin password when auth enabled and both are set
    set:
      auth:
        enabled: true
        adminUsername: adminusername
        adminPassword: adminpassword
    asserts:
      - equal:
          path: data.username
          value: adminusername
          decodeBase64: true
      - equal:
          path: data.password
          value: adminpassword
          decodeBase64: true
    