# Configuration pour APISIX Ingress Controller v2.0.0-rc4

nameOverride: ""
fullnameOverride: ""

podDisruptionBudget:
  enabled: false

autoscaling:
  enabled: false

deployment:
  replicas: 1

  image:
    repository: apache/apisix-ingress-controller
    pullPolicy: IfNotPresent
    tag: "2.0.0-rc4" # Version RC

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  adcContainer:
    image:
      repository: ghcr.io/api7/adc
      tag: "0.21.0"
    config:
      logLevel: "debug"

config:
  logLevel: "debug"
  controllerName: apisix.apache.org/apisix-ingress-controller

  leaderElection:
    id: "apisix-ingress-controller-leader"
    leaseDuration: "15s"
    renewDeadline: "10s"
    retryPeriod: "2s"
    disable: false

  metricsAddr: ":8080"
  enableHTTP2: false
  probeAddr: ":8081"
  secureMetrics: false
  execADCTimeout: "15s"

  provider:
    type: "apisix"
    syncPeriod: "30s"
    initSyncDelay: "10s"

  kubernetes:
    ingressClass: apisix
    defaultIngressClass: true

# Configuration Gateway Proxy pour v2.0.0-rc4
gatewayProxy:
  createDefault: true # ← Activé pour créer la config par défaut
  provider:
    type: ControlPlane
    controlPlane:
      # CORRECTION : Endpoints explicites
      endpoints:
        - "http://apisix-app-admin.apisix-dev.svc.cluster.local:9180"
      auth:
        type: AdminKey
        adminKey:
          value: "changeme-admin-key"

# CORRECTION : Bon namespace
# apisix:
#   adminService:
#     namespace: apisix-dev # ← CORRIGÉ
#     name: apisix-app-admin
#     port: 9180

serviceMonitor:
  enabled: false
