# Configuration fonctionnelle pour APISIX Ingress Controller - Rancher Desktop

# Configuration de base du déploiement
deployment:
  replicas: 1
  
  image:
    repository: apache/apisix-ingress-controller
    pullPolicy: IfNotPresent
    tag: "1.8.0"
  
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Configuration du controller via variables d'environnement
config:
  # Niveau de log pour debug
  logLevel: "debug"
  
  # Configuration Kubernetes
  kubernetes:
    ingressClass: "apisix"
    defaultIngressClass: true
    watchNamespaces: []  # Tous les namespaces
  
  # Configuration APISIX - utilise les valeurs par défaut du chart
  apisix:
    # Le chart va automatiquement découvrir le service APISIX
    adminAPIKey: "edd1c9f034335f136f87ad84b625c8f1"

# Configuration du service APISIX admin
apisix:
  adminService:
    namespace: "apisix-dev"
    name: "apisix-admin"
    port: 9180

# Pas de gateway proxy pour éviter les complications
gatewayProxy:
  createDefault: false

# Service Account et RBAC
serviceAccount:
  create: true
  name: ""

rbac:
  create: true

# Désactiver les fonctionnalités optionnelles
autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

serviceMonitor:
  enabled: false